version: "3.7"

services:
  club_app: &app
    build:
      dockerfile: Dockerfile
      context: .
    command: make docker-run-dev
    container_name: club_app
    environment:
      - MODE=dev
      - DEBUG=true
      - PYTHONUNBUFFERED=1
      - POSTGRES_DB=rationalanswer
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=postgres
      - REDIS_DB=0
      - REDIS_HOST=redis
    restart: 'no'
    volumes:
      - .:/app:delegated # enable hot code reload in debug mode
    depends_on:
      - postgres
      - redis
      - queue
      - webpack
    ports:
      - "8000:8000"

  queue:
    build:
      dockerfile: Dockerfile
      context: .
    command: make docker-run-queue
    environment:
      - MODE=dev
      - DEBUG=true
      - PYTHONUNBUFFERED=1
      - POSTGRES_DB=rationalanswer
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=postgres
      - REDIS_DB=0
      - REDIS_HOST=redis
    restart: 'no'
    volumes:
      - .:/app:delegated
    depends_on:
      - postgres
      - redis

  # Uncomment these lines if you want to test the bot locally
  # bot:
  #   build:
  #     dockerfile: Dockerfile
  #     context: .
  #   command: make docker-run-bot
  #   environment:
  #     - MODE=dev
  #     - DEBUG=true
  #     - PYTHONUNBUFFERED=1
  #     - POSTGRES_DB=rationalanswer
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=postgres
  #     - POSTGRES_HOST=postgres
  #     - REDIS_DB=0
  #     - REDIS_HOST=redis
  #   restart: 'no'
  #   volumes:
  #     - .:/app:delegated
  #   depends_on:
  #     - club_app
  #     - postgres
  #     - redis

  postgres:
    image: postgres:11
    container_name: club_postgres
    restart: 'no'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=rationalanswer
    ports:
      - "5432:5432"

  redis:
    image: redis:alpine
    restart: 'no'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6379:6379"

  webpack:
    image: node:14-slim
    command: npm run watch
    restart: 'no'
    volumes:
      - .:/app:delegated
    working_dir: /app/frontend
