name: Check it could be build and run from scratch

on: [pull_request]

jobs:
  dockerize:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Build the docker-compose stack
        run: docker-compose up -d
      - name: Sleep
        uses: jakejarvis/wait-action@master
        with:
          time: '20s'
      - name: Check db migrate on container
        run: |
          docker-compose exec -T club_app make docker-migrate
      - name: Check build frontend on container
        run: |
          docker-compose exec -T webpack npm run build
