name: Deploy main to production

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Pull new code and restart server
        uses: appleboy/ssh-action@e59c0ee97a7e5240ed9eb489791adbb9c9ac7f6b
        env:
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          MEDIA_HOST: "https://i.rationalanswer.club"
          MEDIA_UPLOAD_URL: "https://i.rationalanswer.club/upload/multipart/"
        with:
          host: ${{ secrets.PRODUCTION_SSH_HOST }}
          username: ${{ secrets.PRODUCTION_SSH_USERNAME }}
          key: ${{ secrets.PRODUCTION_SSH_KEY }}
          envs: POSTGRES_PASSWORD,MEDIA_UPLOAD_URL
          script: cd rationalanswer.club && git pull && make redeploy
